### ISSUE TITLE
[New command] `map_id(name)` (finding maps' identifiers by their name)

### ISSUE THREAD

**Issue by LucasDevos** [RMEx/RME#417]
## New command's proposal
`map_id` already exists but only returns the current map's id.
Would be great if "name" was an optional argument to return the id of the map with this name.

### Command's definition
Returns the id of the current map. If `name` is specified, returns the id of the map with that name.

#### Command's purpose
Allows to specify maps by name rather than by id - it's a bit more intuitive. Example:
`player_teleport(map_id("City"),0,0)`
Or, for example, for a game with various seasons:
`player_teleport(map_id("City_"+@season_name),0,0)`

If several maps have that name, I guess it should simply returns the first occurence found.

#### Command's syntax
`map_id(*name)`
`name` is a string corresponding to the map name
It returns the id of the map, or `nil` if no map with this name was found.

**Comment by acs-l** [comment]
The only issue that I see there -- _and that's more a remark than anything_ -- is that maps' names are not injective regarding maps' identifiers. Therefore, for a given `name`, we can return several maps' identifiers.

For instance, let's say that I have two maps which shares the same name:
 - (`map_id = 1`, `name = 'Stormwind'`)
 - (`map_id = 2`, `name = 'Stormwind'`)
 - (`map_id = 3`, `name = 'Stormwind castle'`)

```ruby
map_id('Stormwind')
# would return: [1, 2]
```

---

Otherwise, I like the idea of finding maps by their name instead of their internal identifiers. That's a whole lot more convenient !

In addition to support `String` (_map's exact name_) I think that it would be suitable to support regular expression as well (_finding all maps whose name start with `"City"`_), wouldn't it ?

**Comment by Zer0xxxxx** [comment]
@acs-l According to my mind, it would be great to support regular expression, or even parsing as well! :+1:
